architecture: {{ .architecture }}

actions:
  - action: apt
    description: Basic packages
    packages:
      - locales

  - action: overlay
    description: Locale overlay
    source: ../overlays/17-locales
    destination: /

  - action: run
    description: Set up system locale
    chroot: true
    command: |
      dpkg-reconfigure --frontend=noninteractive locales
      update-locale LANG=en_US.UTF-8

  - action: run
    description: Set default timezone
    chroot: true
    command: |
      echo "America/Los_Angeles" > /etc/timezone
      rm /etc/localtime
      ln -sf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime