#!/bin/bash
# NEON AI (TM) SOFTWARE, Software Development Kit & Application Framework
# All trademark and other rights reserved by their respective owners
# Copyright 2008-2022 Neongecko.com Inc.
# Contributors: Daniel McKnight, Guy Daniels, Elon Gasper, Richard Leeds,
# Regina Bloomstine, Casimiro Ferreira, Andrii Pernatii, Kirill Hrymailo
# BSD-3 License
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from this
#    software without specific prior written permission.
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
# OR PROFITS;  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE,  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Set default configurations
PULSE_SYSTEM=/etc/pulse/pulseaudio-system.pa
PULSE_DAEMON=/etc/pulse/pulseaudio-daemon.conf

# Check sj201 revision if package is available
if which sj201; then
  [ "$(sj201 get-revision)" != "0" ] && prefix="sj201-"
fi

# Check platform defaults
if [ -z "${prefix}" ]; then
  if [[ "$(uname -r)" == *"rockchip-rk3588" ]]; then
    # Check for Orange Pi
    prefix="opi5-"
    card=$(aplay -l | grep "es8388" | cut -d ':' -f 1 | cut -d ' ' -f 2)
    # TODO: Validate below params
    tinymix -D "${card}" set 3 4
    tinymix -D "${card}" set 4 2
    tinymix -D "${card}" set 14 192
    tinymix -D "${card}" set 16 0
    tinymix -D "${card}" set 17 0
    tinymix -D "${card}" set 31 1
    tinymix -D "${card}" set 32 1
    tinymix -D "${card}" set 33 1
  elif which dtoverlay; then
    # If dtoverlay command is present, assume RPi
    prefix="rpi-"
  fi
fi

if [ -n "${prefix}" ]; then
  PULSE_SYSTEM="${prefix}system.pa"
  PULSE_DAEMON="${prefix}daemon.conf"
fi

if [[ -f /etc/pulse/system.pa || -L /etc/pulse/system.pa ]] ; then
    rm /etc/pulse/system.pa
fi
if [[ -f /etc/pulse/daemon.conf || -L /etc/pulse/daemon.conf ]] ; then
    rm /etc/pulse/daemon.conf
fi

ln -s "${PULSE_SYSTEM}" /etc/pulse/system.pa
ln -s "${PULSE_DAEMON}" /etc/pulse/daemon.conf