#!/bin/bash

# Set default configurations
PULSE_SYSTEM=/etc/pulse/pulseaudio-system.pa
PULSE_DAEMON=/etc/pulse/pulseaudio-daemon.conf

rev=$(sj201 get-revision)

if [[ $? == 1 && "${rev}" != "0" ]]; then
  echo "Configure SJ201 Audio"
  prefix="sj201-"
fi

if [ -n "${prefix}" ]; then
  PULSE_SYSTEM="${prefix}system.pa"
  PULSE_DAEMON="${prefix}daemon.conf"
fi

if [[ -f /etc/pulse/system.pa || -L /etc/pulse/system.pa ]] ; then
    rm /etc/pulse/system.pa
fi
if [[ -f /etc/pulse/daemon.conf || -L /etc/pulse/daemon.conf ]] ; then
    rm /etc/pulse/daemon.conf
fi

ln -s "${PULSE_SYSTEM}" /etc/pulse/system.pa
ln -s "${PULSE_DAEMON}" /etc/pulse/daemon.conf