#!/bin/sh -e

. /scripts/functions

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

# Stop udevd, we'll miss a few events while we run init, but we catch up
udevadm settle
udevadm control --exit

# move the /dev tmpfs to the rootfs; fall back to util-linux mount that does
# not understand -o move
mount -n -o move /dev "${rootmnt:?}/dev" || mount -n --move /dev "${rootmnt}/dev"

# create a temporary symlink to the final /dev for other initramfs scripts
nuke /dev

ln -s "${rootmnt}/dev" /dev || panic "Failed to link /dev"
log "linked ${rootmnt}/dev to /dev"
