#!/bin/bash
# NEON AI (TM) SOFTWARE, Software Development Kit & Application Framework
# All trademark and other rights reserved by their respective owners
# Copyright 2008-2022 Neongecko.com Inc.
# Contributors: Daniel McKnight, Guy Daniels, Elon Gasper, Richard Leeds,
# Regina Bloomstine, Casimiro Ferreira, Andrii Pernatii, Kirill Hrymailo
# BSD-3 License
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from this
#    software without specific prior written permission.
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
# OR PROFITS;  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE,  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

validate_mark2() {
  if [ "$(sj201 get-revision)" == "0" ]; then
    echo "Mark2 image booted but no SJ201 hardware detected"
    exit 0
  fi
  if [ ! -e /dev/fb0 ]; then
    # Display not loaded; there is no way to recover this without a hard reset
    # to re-init the Pi hardware. Do our best to communicate to the user what
    # has happened so they are able to manually reboot the system until a better
    # solution is available
    echo "Screen not initialized! Notify the user..."
    sj201 reset-led yellow
    shutdown now
  fi
  if [ "$(cat /sys/class/backlight/rpi_backlight/brightness)" == "0" ]; then
    echo "Backlight off! Set to minimum value"
    echo "1" > /sys/class/backlight/rpi_backlight/brightness
  fi
  while ! journalctl -u gui-shell | grep "Trying to connect to Mycroft"; do
    echo "Waiting for GUI service init"
    sleep 1
  done
  if journalctl -u gui-shell | grep "code=-13"; then
    echo "GUI failed to start! Restarting..."
    reboot now
  fi
  echo "Mark2 boot validated"
}

validate_rpi4() {
  echo "No validation implemented"
}

validate_opi5() {
  echo "No validation implemented"
}

# Check for file flag to skip validation
[ -f /boot/firmware/skip_preflight_check ] && exit 0

build_meta="/opt/neon/build_info.json"
[ -f ${build_meta} ] || exit 0
device="$(grep "device" ${build_meta} | cut -d'"' -f4)"
if [ "${device}" == "mark_2" ]; then
  validate_mark2
elif [ "${device}" == "rpi4" ]; then
  validate_rpi4
elif [ "${device}" == "opi5" ]; then
  validate_opi5
fi

exit 0
