#!/bin/bash
# NEON AI (TM) SOFTWARE, Software Development Kit & Application Framework
# All trademark and other rights reserved by their respective owners
# Copyright 2008-2022 Neongecko.com Inc.
# Contributors: Daniel McKnight, Guy Daniels, Elon Gasper, Richard Leeds,
# Regina Bloomstine, Casimiro Ferreira, Andrii Pernatii, Kirill Hrymailo
# BSD-3 License
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from this
#    software without specific prior written permission.
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
# OR PROFITS;  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE,  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root"
  exit 1
fi
. /etc/neon/versions.conf

branch=${1:-"${NEON_CORE_REF}"}
device=${NEON_OS_DEVICE:-"mark_2"}

# TODO: Case statement here
[ "${device}" == "mark_2" ] && update_path="pi/mycroft_mark_2"
platform=${PLATFORM:-"rpi4"}
initramfs_url="https://github.com/NeonGeckoCom/neon_debos/raw/${branch}/overlays/02-rpi4/boot/firmware/initramfs"
squashfs_url="https://2222.us/app/files/neon_images/${update_path}/updates/${branch}/"

# Update initramfs
wget "${initramfs_url}" -O /opt/neon/initramfs.tmp || exit 10
mv /opt/neon/initramfs.tmp /opt/neon/initramfs
/opt/neon/update_firmware_file.sh "/opt/neon/initramfs" "/opt/neon/firmware/initramfs" && echo "Updated initramfs"

squashfs_links=$(wget -qO- "${squashfs_url}")

while IFS= read -r line; do
  if grep -q ".squashfs" <<< "${line}"; then
    line="${line#*href=\"}"
    keep="${line%%\">*}"
  fi
done <<< "${squashfs_links}"
squashfs_url="${squashfs_url}${keep}"
wget "${squashfs_url}" -O /opt/neon/update.tmp || exit 10
mv /opt/neon/update.tmp /opt/neon/update.squashfs && echo "OS will update on next boot"
