# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      ARCH: arm64
      RECIPE: ovos-dev-edition-rpi4

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update APT
        run: sudo apt-get update
        
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
         key: ${{ secrets.OVOS_DOWNLOADS_SYNC_KEY }} 
         known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
         
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.OVOS_DOWNLOADS_HOST }} >> ~/.ssh/known_hosts

      # Runs a single command using the runners shell
      - name: Install Debos Deps
        run: sudo apt-get install git bmap-tools dosfstools e2fsprogs zsync rsync -y

      - name: Try Setup Loop Device
        run:  sudo losetup -f

      - name: Git clone required debos recipe
        run: git clone https://github.com/OpenVoiceOS/ovos_debos_dev_edition ovos-debos

      # Runs a set of commands using the runners shell
      #- name: Run a Debos Recipe
      #  run: cd ovos-debos && docker run --rm --tmpfs /scratch:exec --workdir $(pwd) --mount type=bind,source=$(pwd),destination=$(pwd) --group-add=108 --security-opt label=disable -e TMP=/scratch godebos/debos ovos-dev-edition-rpi4.yml -b uml -t architecture:arm64 -m 10G
      
      #- name: Deploy Image
      #  run: rsync -avz $(pwd)/ovos-debos/ovos-dev-edition-rpi4.img ${{ secrets.OVOS_DOWNLOADS_USER }}@${{ secrets.OVOS_DOWNLOADS_HOST }}:/var/www/html/
        
      - name: Cleanup Workspace
        run: rm -rf $(pwd)/ovos-debos
