# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      ARCH: arm64 
      RECIPE: ovos-dev-edition-rpi4

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Update APT
        run: sudo apt-get update

      # Runs a single command using the runners shell
      - name: Install Debos Deps
        run: sudo apt-get install debos bmap-tools dosfstools e2fsprogs zsync -y
      
      - name: Run losetup to check list of loopback devices
        run: losetup
      
      # Runs a set of commands using the runners shell
      - name: Run a Debos Recipe
        run: debos --disable-fakemachine --memory=6G -t architecture:${ARCH} ${RECIPE}.yml
