# This workflow will generate a distribution and upload it to PyPI

name: Publish Alpha Build
on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'version.py'
      - 'CHANGELOG.md'

jobs:
  publish_alpha_release:
    uses: neongeckocom/.github/.github/workflows/publish_alpha_release.yml@master
    secrets: inherit
    with:
      version_scheme: "dated"
      version_file: "version.py"
      setup_py: "version.py"
      publish_pypi: false
      publish_prerelease: true
      update_changelog: true
  trigger_os_build:
    runs-on: ubuntu-latest
    needs: publish_alpha_release
    steps:
      - name: Call Release Action
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{secrets.NEON_OS_TOKEN}}
          repository: neongeckocom/neon-os
          event-type: Publish Release
          client-payload: |-
            {
              "ref": "dev",
              "repo": "neon-debos"
            }