# This workflow will run unit tests

name: Test Base Image Download
on:
  pull_request:
  workflow_dispatch:

jobs:
  validate_image_download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install test dependencies
        run: |
          sudo apt update
          sudo apt install -y pipx
          sudo pipx install pytest
      - name: Run Tests
        run: |
          pytest test/
