# This workflow will run unit tests

name: Test Skill
on:
  pull_request:
  workflow_dispatch:

jobs:
  validate_image_download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout repository
      - name: Check base images
        run: |
          python3 base_images/download_base_images.py
          [ -f base_images/rpi4_base.tar.gz ] || exit 10
          [ -f base_images/opi5_base.tar.gz ] || exit 10
