# This workflow will run unit tests

name: Test Skill
on:
  pull_request:
  workflow_dispatch:

jobs:
  validate_image_download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - name: Check base image downloads
        run: |
          sudo apt update
          sudo apt install -y python3-pytest
          pytest test/
