# This workflow will run unit tests

name: Test Skill
on:
  pull_request:
  workflow_dispatch:

jobs:
  validate_image_download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout repository
      - name: Check base images
        run: |
          pytest test/
